title: Dice to See You
tagline: A blog
baseurl: /
url: http://www.dice2cu.com
email: contact@dice2cu.com
paginate: 5
timezone: America/Chicago
exclude:
  - README.md
  - Gemfile
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"